version: '3'
services:
  server:
    image: myspecialway/msw-server:latest
    restart: always
    links:
      - mongodb
    ports:
      - 3000:3000
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/msw-test
      - DB_NAME=msw-test
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
  cient:
    build: .
    image: msw-portal:e2e
    ports:
      - "4200:80"
    links:
      - server
    environment:
      - NODE_ENV=e2e-tests
