#!/bin/sh

# install kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

# copy kubeconfig
mkdir ${HOME}/.kube
cp ./scripts/k8s/config ${HOME}/.kube/config

# inject base64 encoded values
kubectl config set users.clusterUser_MSWPPR_myspecialway.client-certificate-data "$KUBE_CLIENT_CERTIFICATE"
kubectl config set users.clusterUser_MSWPPR_myspecialway.client-key-data "$KUBE_CLIENT_KEY"

# ignore certificate validity -- BAD --
kubectl --insecure-skip-tls-verify

kubectl get nodes
