#!/bin/sh

# install kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

# copy kubeconfig
mkdir ${HOME}/.kube
cp ./scripts/k8s/config ${HOME}/.kube/config

kubectl config set clusters.mswAKSCluster.certificate-authority-data "$KUBE_CLUSTER_CERTIFICATE"
kubectl config set users.clusterUser_MySpecialWayDev_mswAKSCluster.client-certificate-data "$KUBE_CLIENT_CERTIFICATE"
kubectl config set users.clusterUser_MySpecialWayDev_mswAKSCluster.client-key-data "$KUBE_CLIENT_KEY" --token="$KUBE_TOKEN"

kubectl get nodes
