#!/bin/bash

docker pull nginx:stable
if [ "$TRAVIS_PULL_REQUEST" != "false" ]
then
    echo info::docker:: branch is a pull request, skipping docker
elif [ "$BRANCH" = 'master' ]
then
   echo info::docker:: build is on \"master\" branch incrementing version and building
   docker pull node:carbon
   yarn version --new-version patch
   build . -t myspecialway/msw-portal:$(./scripts/echo-version package.json) -t myspecialway/msw-portal:latest
else
    echo info::docker:: branch $BRANCH is not master, building without version increment
    docker pull node:carbon
    docker build . -t myspecialway/msw-portal:$(echo $BRANCH | sed 's/\///g')
fi
